### ISSUE TITLE
클래스명 변경

### ISSUE THREAD

**Issue by Achelous1** [Matzip-Neighbors/MatDi-API#23]
https://github.com/Matzip-Neighbors/MatDi-API/blob/8537922c5ec3154f07f836c0f9219b292d6e2305/src/main/java/com/mn/matdi/controller/MailController.java#L13

* 해당 클래스는 인증을 하는 목적의 클래스니 MailController 보다는 UserVerificationController로 명명하는 것이 더 타당해 보입니다

**Comment by yarogono** [comment]
해당 내용 반영해서 feat/email-verify 브랜치에 푸쉬 해놨습니다.
기존 MailController는 이메일 인증에 대한 기능을 제대로 못 나타내는 것이라는걸 알게됐네요.
감사합니다 친슈님
